trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
     - job: Build
       displayName: Build job
       pool: Default
       steps:
         # Task-1: Build Docker Image and push to Azure Container Registry ACR
         - task: Docker@2
           inputs:
             containerRegistry: 'demoacr'
             repository: 'app1'
             command: 'buildAndPush'
             Dockerfile: '**/Dockerfile'
             tags: 
               $(tag)
        
         # Task 2 publish build artifacts
         - task: PublishPipelineArtifact@1
           inputs:
            targetPath: '$(Pipeline.Workspace)/s/kube-manifests'
            artifact: 'drop'
            publishLocation: 'pipeline'